# Lab04 - Sparsity Aware Learning
Author: [Yunting Chiu](https://www.linkedin.com/in/yuntingchiu/)

# Exercise 1


In [1]:
# Install the libraries
import random
import numpy as np
import matplotlib.pyplot as plt
from functools import reduce
%matplotlib inline
plt.style.use(['ggplot'])

## 1A

In [2]:
X = np.array([[0.5, 2, 1.5], [2, 2.3, 3.5]]) # matrix X
theta = np.array([2.5, 0, 0], ndmin = 2).T 
y = np.dot(X, theta)
print(theta)

[[2.5]
 [0. ]
 [0. ]]


In [3]:
print(X)

[[0.5 2.  1.5]
 [2.  2.3 3.5]]


In [4]:
print(y)

[[1.25]
 [5.  ]]


According to the textbook 9.10, we can know the L2 minimizer accepts the closed from the following solution: 

$$
\hat{\theta} = X^T (XX^T)^{-1} y
$$
where $X^T (XX^T)^{-1}$ (a m × n matrix) is called a pseudo-inverse.

In [5]:
# theta2 = np.dot(np.dot(X.T, np.linalg.inv(np.dot(X, X.T))), y)
theta2 = np.dot(np.dot(X.T, np.linalg.inv(np.dot(X, X.T))), y)
error_L2 = np.linalg.norm(y - np.dot(X, theta2))
error_theta = np.linalg.norm(theta2 - theta)
print('The L2 norm minimized solution is {}'.format(theta2))

The L2 norm minimized solution is [[ 1.08637128]
 [-0.49775659]
 [ 1.13488503]]


In [6]:
print(" The error achieved with L2 norm minimization is {}".format(error_L2))

 The error achieved with L2 norm minimization is 4.636427468134552e-15


There is an existing funcation called `numpy.linalg.pinv` of pseudoinverse of X matrix, the outcome is also the same as the previous formula.

In [7]:
pesu_X_ex1 = np.dot(X.T, np.linalg.inv((np.dot(X, X.T))))
print(pesu_X_ex1)
print("---------------------------")
pesu_X_ex2 = np.linalg.pinv(X)
print(pesu_X_ex2)

[[-0.49040942  0.33987661]
 [ 0.81323612 -0.30286035]
 [-0.25417835  0.29052159]]
---------------------------
[[-0.49040942  0.33987661]
 [ 0.81323612 -0.30286035]
 [-0.25417835  0.29052159]]


## 1B

We need to estimate the smallest number of parameters that can be explained the obtained observations. Consider all possible combinations of zero in $\theta$, removing the respective columns of X and check whether the system of equations is satisifed. 

Let's start checking for possible 1-sparse solution.

### Check solution [x, 0, 0]
This one has the ideal solution, the $\theta_0$ lead to zero estimation error.

In [ ]:
subX_11 = np.array(X[:, 0], ndmin = 2).T # ndmin = Number of array dimensions
# print(subX_11)
theta_11 = np.zeros((3, 1))
theta_11[0] = np.dot(np.linalg.inv(np.dot(subX_11.T, subX_11)), np.dot(subX_11.T, y))
print(theta_11)
error1 = np.linalg.norm(y - np.dot(X, theta_11)) #check that theta_11 is a solution
error_theta1 = np.linalg.norm(theta_11 - theta)
print('Achieved error: %.20f'% error1)
print('Achieved error in theta %.20f'% error_theta1)

### Check solution [0, x, 0]

In [ ]:
subX_12 = np.array(X[:, 1], ndmin = 2).T # ndmin = Number of array dimensions
# print(subX_22)
theta_12 = np.zeros((3, 1))
theta_12[1] = np.dot(np.linalg.inv(np.dot(subX_12.T, subX_12)), np.dot(subX_12.T, y))
print(theta_12)
error2 = np.linalg.norm(y - np.dot(X, theta_12)) #check that theta_22 is a solution
error_theta2 = np.linalg.norm(theta_12 - theta)
print('Achieved error: %.20f'% error2)
print('Achieved error in theta %.20f'% error_theta2)

### Check solution [0, 0, x]

In [ ]:
subX_13 = np.array(X[:, 2], ndmin = 2).T # ndmin = Number of array dimensions
# print(subX_22)
theta_13 = np.zeros((3, 1))
theta_13[2] = np.dot(np.linalg.inv(np.dot(subX_13.T, subX_13)), np.dot(subX_13.T, y))
print(theta_13)
error3 = np.linalg.norm(y - np.dot(X, theta_13)) # check that theta2 is a solution
error_theta3 = np.linalg.norm(theta_13 - theta)
print('Achieved error: %.20f'% error3)
print('Achieved error in theta %.20f'% error_theta3)

In [11]:
theta0 = theta_11 # because this combination has the lowest error
print("With zero estimation error of {}, we can skip for searching 2-sparse solutions".format(theta0))

With zero estimation error of [[2.5]
 [0. ]
 [0. ]], we can skip for searching 2-sparse solutions


## 1C
As the $\theta_2$ is the smaller one in L2 norms, which makes sense.

In [ ]:
print("L2 norm of theta 0 is {}".format(np.linalg.norm(theta0)))
print("L2 norm of theta 2 is {}".format(np.linalg.norm(theta2)))
if np.linalg.norm(theta0) > np.linalg.norm(theta2):
  print("theta2 is the smaller one")
else:
  print("theta0 is the smaller one")

# Exercise 2 Image Denoising

## 2A

# Testing Zone

In [ ]:
print('Check solution [x, 0, 0]')
theta_11 = np.zeros((3, 1))
# print(theta_11)
subX_11 = np.array(X[:, 0], ndmin = 2).T

theta_11[0] = np.dot(np.linalg.inv(np.dot(subX_11.T, subX_11)), np.dot(subX_11.T, y))
print(theta_11)
error1 = np.linalg.norm(y - np.dot(X, theta_11)) #check that theta_11 is a solution
error_theta1 = np.linalg.norm(theta_11 - theta)

print('Achieved error: %.20f'% error1)
print('Achieved error in theta %.20f'% error_theta1)
print('--------------')

# Output

In [ ]:
# should access the Google Drive files before running the chunk
%%capture
!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic 
!jupyter nbconvert --to pdf "/content/drive/MyDrive/American_University/2021_Fall/DATA-642-001_Advanced Machine Learning/GitHub/Labs/04/submit/Lab4_Yunting.ipynb"