# Lab04 - Sparsity Aware Learning
### Author: [Yunting Chiu](https://www.linkedin.com/in/yuntingchiu/)

In [2]:
# Install the libraries
import random
import numpy as np
import matplotlib.pyplot as plt
from functools import reduce
%matplotlib inline
plt.style.use(['ggplot'])

In [39]:
X = np.array([[0.5, 2, 1.5], [2, 2.3, 3.5]])
theta = np.array([2.5, 0, 0], ndmin = 2).T 
y = np.dot(X, theta)
print(theta)

[[2.5]
 [0. ]
 [0. ]]


In [40]:
print(X)

[[0.5 2.  1.5]
 [2.  2.3 3.5]]


In [41]:
print(y)

[[1.25]
 [5.  ]]


In [30]:
theta2 = np.dot(np.dot(X.T, np.linalg.inv(np.dot(X, X.T))), y)
error_L2 = np.linalg.norm(y - np.dot(X, theta2))
error_theta = np.linalg.norm(theta2 - theta)

In [34]:
pseu_X = np.linalg.pinv(X)
print(pseu_X)

[[-0.49040942  0.33987661]
 [ 0.81323612 -0.30286035]
 [-0.25417835  0.29052159]]


In [55]:
theta2 = np.dot(np.dot(X.T, np.linalg.inv(np.dot(X, X.T))), y)
error_L2 = np.linalg.norm(y -np.dot(X, theta2))
error_theta = np.linalg.norm(theta2 - theta)
print(theta2)

[[ 1.08637128]
 [-0.49775659]
 [ 1.13488503]]


In [56]:
print('Check solution [x, 0, 0]')
theta_11 = np.zeros((3, 1))
# print(theta_11)
subX_11 = np.array(X[:, 0], ndmin = 2).T

theta_11[0] = np.dot(np.linalg.inv(np.dot(subX_11.T, subX_11)), np.dot(subX_11.T, y))
print(theta_11)
error1 = np.linalg.norm(y - np.dot(X, theta_11)) #check that theta_11 is a solution
error_theta1 = np.linalg.norm(theta_11 - theta)

print('Achieved error: %.20f'% error1)
print('Achieved error in theta %.20f'% error_theta1)
print('--------------')

Check solution [x, 0, 0]
[[2.5]
 [0. ]
 [0. ]]
Achieved error: 0.00000000000000000000
Achieved error in theta 0.00000000000000000000
--------------
